name: hiersigcwganenv
channels:
  - defaults
  - pytorch
dependencies:
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - openssl=1.1.1h=he774522_0
  - pip=20.2.3=py38_0
  - python=3.8.3=he1778fa_2
  - setuptools=49.6.0=py38_1
  - sqlite=3.33.0=h2a8f88b_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=py_0
  - wincertstore=0.2=py38_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - cycler==0.10.0
    - joblib==0.17.0
    - kiwisolver==1.2.0
    - matplotlib==3.3.2
    - numpy==1.19.2
    - pandas==1.0.3
    - pillow==7.2.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - signatory==1.2.1.1.4.0
    - six==1.15.0
    - threadpoolctl==2.1.0
    - https://download.pytorch.org/whl/cu101/torch-1.4.0-cp38-cp38-win_amd64.whl  # torch==1.4.0 gpu cuda 10.1
    - https://download.pytorch.org/whl/cu101/torchvision-0.5.0-cp38-cp38-win_amd64.whl  # torch==0.5.0 gpu cuda 10.1
    - tqdm==4.50.0
prefix: C:\Users\fdemeer\AppData\Local\conda\conda\envs\sigcwganenv

